#!/bin/bash

# Author: Loka Sainadh
# Date: 26-11-2023
# Description: This script will add system inventory to database file
# Modified: 26-11-2023

echo "Please enter hostname ..?"
read host
echo
        grep -q $host /home/ec2-user/shell-scripts/inventory/database
        if [ $? -eq 0 ]
        then
        echo "ERROR -- hostname $host already exist"
        echo
        exit 0
        fi 

echo "Please enter IP address ..?"
read IP
echo        
        grep -1 $IP /home/ec2-user/shell-scripts/inventory/database
        if [ $? -eq 0 ]
        then
        echo "ERROR --- IP Address $IP already exist"
        echo
        exit 0
        fi 

echo "Please enter description .."
read description
echo

echo $host $IP $description >> /home/ec2-user/shell-scripts/inventory/database
echo "The provided record has been added"
echo

