#!/bin/bash

# Author: Loka Sainadh
# Date: 26-11-2023
# Description: This script will check the disk space
# Modified: 26-11-2023

a=`df -h | egrep -v "devtmpfs|tmpfs" | tail -n+2 | awk '{print $5}' | cut -d'%' -f1`

for i in $a 
do 
    if [ $i -ge 10 ]
    then
            echo Check Disk Space $i `df -h | grep $i`
    fi
done
