#!/bin/bash

# Author: Loka Sainadh
# Date: 26-11-2023
# Description: This script will check the disk space while read output
# Modified: 26-11-2023

df -H | grep -vE '^Filesystem|tmpfs|cdrom' | awk '{print $5,$1}' | while read output
do
        usep=$(echo $output | awk '{print $1}' | cut -d'%' -f1  )
        partition=$(echo $output | awk '{print $2}' )
        
	if [ $usep -ge 10 ]
	then
        echo "Running out of space \"$partition ($usep%)\" on $(hostname) as on $(date)"
        fi
done
