#!/bin/bash

# Author: Loka Sainadh
# Date: 26-11-2023
# Description: Assigning Permissions from ls to the files.
# Modified: 26-11-2023

total=$(ls -lrt hello.* | wc -l)

echo "It will take $total seconds to assign permissions"

for i in hello.*
do 
    echo "Assigning Write Permissions to $i"
    chmod a+w $i
    sleep 1
done

