#!/bin/bash

# Author: Loka sainadh
# Date: 26-11-2023
# Description: This script displays the numbers using for Loop in simple count
# Modified: 26-11-2023

for i in {1..10}
do 
        echo $i
        sleep 1
done
