#!/bin/bash

# Author: Loka Sainadh
# Date: 26-11-2023
# Description: This script creates the user account
# Modified: 26-11-2023

echo "Please provide a username?"
read u
echo

grep -q $u /etc/passwd
        if [ $? -eq 0 ]
        then
        echo ERROR -- User $u already exist
        echo Please choose another username
        echo
        exit 0
        fi

useradd $u
echo $u account has been created
